### ISSUE TITLE
npx palico init gives error 'sh: palico: command not found'

### ISSUE THREAD

**Issue by sammcj** [palico-ai/palico-main#153]
Running the app as per the readme gives the following error:

```shell
npx palico init testapp
sh: palico: command not found
```

**Comment by shikdernyc** [comment]
Hmm weird, I was able to run this command on stackblitz without any issue: https://stackblitz.com/edit/stackblitz-starters-4vgwmr?file=testapp%2Fpackage.json

Can you try updating your npm and rerunning the command?
```
npm install -g npm
npx palico init testapp
```

Or manually install palico first
```
npm install -g palico
palico init testapp
```

**Comment by sammcj** [comment]
The npm install -g did it! Thanks :)
